### ISSUE TITLE
都是因为你这个习禁评机器人，我被骂了

### ISSUE THREAD

**Issue by madaraful** [abusetelegram/xixi-haha#6]
![20210404_144249](https://user-images.githubusercontent.com/80938648/113503819-d5bbf580-9566-11eb-9fa1-b3e408692010.jpg)

确实，这种粉红五毛发言，虽然是机器人发的，但是仍然是垃圾内容。

![20210404_160626](https://user-images.githubusercontent.com/80938648/113503878-2b909d80-9567-11eb-8b4d-de41dff778e7.jpg)

习禁评确实被禁评了。

**Comment by madaraful** [comment]
群：https://t.me/tgInternetSecurity

群日志：https://t.me/tgInternetSecurityLog

**Comment by NeverBehave** [comment]
![Screenshot_20210404-053447](https://user-images.githubusercontent.com/17120571/113504687-ac1fb180-9507-11eb-85bf-575a95e8f7a4.jpg)

没有意识到这个项目是用来嘲讽的哈哈哈哈哈好吧看来还得再明显点
